name: docker-file test


on: [push]


jobs:
  run-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # the "docker" command appears to already exist on this github action.
      # - name: install docker 
      #   run: |
      #     curl -sSL https://get.docker.com/ | sudo sh

      - name: Build docker file
        run: |
          docker build -t sample-node-express .
          docker images

      - name: Run docker file
        run: |
          docker run -p 3000:3000 -d sample-node-express
          docker ps

      - name: connect to web service
        run: | 
          curl http://localhost:3000/ | sudo sh