name: ssh

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 在 $GITHUB_WORKSPACE 下簽出您的存儲庫，以便您的工作可以訪問它
      - uses: actions/checkout@v4

      - name: ssh to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            exec bash \-l
            cd ~/project-dir
            ./deploy.sh
            cd shopping-website
            docker-compose stop   
            git pull origin main
            npm install
            npm run migrate  
            docker-compose up -d
            
            
          # docker build -t my-web-app . && 
            # docker build -t my-consumer-app -f ./kafka/Dockerfile . && 
            # export NVM_DIR=~/.nvm &&
            # source ~/.nvm/nvm.sh &&
            # npm --help &&