name: ssh

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 在 $GITHUB_WORKSPACE 下簽出您的存儲庫，以便您的工作可以訪問它
      - uses: actions/checkout@v4

      - name: ssh to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: mkdir -p test
        