name: ssh

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 在 $GITHUB_WORKSPACE 下簽出您的存儲庫，以便您的工作可以訪問它
      - uses: actions/checkout@v4

      - name: ssh to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script:  
            cd shopping-website && 
            docker compose down && 
            git pull origin main &&
            cat "${{ secrets.ENV }}" > .env &&
            cat "${{ secrets.AWS_RDS_CONFIG }}" > ./config/aws_rds_config.js && 
            docker build -t my-web-app . && 
            docker build -t my-consumer-app -f ./kafka/Dockerfile . && 
            npm install && 
            npm run migrate && mkdir -p github_action_success
            # docker-compose up -d 